[window]
dimensions = { columns = 120, lines = 31 }
opacity = 0.9
padding = { x = 5, y = 5 }

[font]
normal = { family = "Inconsolata Nerd Font Mono", style = "Regular" }
bold = { family = "Inconsolata Nerd Font Mono", style = "Bold" }
italic = { family = "Inconsolata Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Inconsolata Nerd Font Mono", style = "Italic" }

size = 12.00
